// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYEcA5Ql1Kr_oMavT9x9VHHvaVmS2itV8',
    appId: '1:122679835057:web:650a8497d1493e1c286590',
    messagingSenderId: '122679835057',
    projectId: 'realtime-quiz-app-a13f8',
    authDomain: 'realtime-quiz-app-a13f8.firebaseapp.com',
    databaseURL: 'https://realtime-quiz-app-a13f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-a13f8.appspot.com',
    measurementId: 'G-9E6QQHTGY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4oOdr-j7DJEpuvQXYzVDjmW0o_q9dEmU',
    appId: '1:122679835057:android:879371eacc39fd1f286590',
    messagingSenderId: '122679835057',
    projectId: 'realtime-quiz-app-a13f8',
    databaseURL: 'https://realtime-quiz-app-a13f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-a13f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvSEqUYhXXqrPjy0E3tN0Qk3O8D6f_fIw',
    appId: '1:122679835057:ios:996ce1e3cc6a056d286590',
    messagingSenderId: '122679835057',
    projectId: 'realtime-quiz-app-a13f8',
    databaseURL: 'https://realtime-quiz-app-a13f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-a13f8.appspot.com',
    iosBundleId: 'com.example.realtimeQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvSEqUYhXXqrPjy0E3tN0Qk3O8D6f_fIw',
    appId: '1:122679835057:ios:996ce1e3cc6a056d286590',
    messagingSenderId: '122679835057',
    projectId: 'realtime-quiz-app-a13f8',
    databaseURL: 'https://realtime-quiz-app-a13f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-a13f8.appspot.com',
    iosBundleId: 'com.example.realtimeQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYEcA5Ql1Kr_oMavT9x9VHHvaVmS2itV8',
    appId: '1:122679835057:web:a9476813700c83bd286590',
    messagingSenderId: '122679835057',
    projectId: 'realtime-quiz-app-a13f8',
    authDomain: 'realtime-quiz-app-a13f8.firebaseapp.com',
    databaseURL: 'https://realtime-quiz-app-a13f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-a13f8.appspot.com',
    measurementId: 'G-4V9NK7K70T',
  );
}
